kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: jarry6/drone-flutter
      tags: 3
      username: jarry6
      password:
        from_secret: docker_password
trigger:
  branch:
    - master
